// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmzfdqcmfjtjcvcxxsjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtemZkcWNtZmp0amN2Y3h4c2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjMzODksImV4cCI6MjA3MDEzOTM4OX0.h4kpG3SE3tbxdAtD0nH0ZzF_ZWLb7t9PTRbo9NTqpII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});